---
nodesource_apt_key_url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
nodesource_apt_key_path: /etc/apt/keyrings/nodesource.asc
nodesource_apt_repository_url: https://deb.nodesource.com/node_22.x
nodesource_package_name: nodejs
