apiVersion: v1
kind: PersistentVolume
metadata:
  name: shelfsense-postgres-pv
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/name: shelfsense
    app.kubernetes.io/instance: shelfsense
    app.kubernetes.io/managed-by: infrastructure
    app.kubernetes.io/part-of: shelfsense-it
    app.kubernetes.io/component: postgres
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /srv/shelfsense/postgres
    type: Directory
