apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.postgres.persistence.pvName }}
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "shelfsense.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  capacity:
    storage: {{ .Values.postgres.persistence.size }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.postgres.persistence.accessMode }}
  persistentVolumeReclaimPolicy: {{ .Values.postgres.persistence.reclaimPolicy }}
  storageClassName: {{ .Values.postgres.persistence.storageClassName | quote }}
  hostPath:
    path: {{ .Values.postgres.persistence.hostPath | quote }}
    type: Directory
