apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "shelfsense.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  clusterIP: None
  ports:
    - name: postgres
      port: {{ .Values.database.service.port }}
      targetPort: {{ .Values.database.service.port }}
  selector:
    {{- include "shelfsense.postgres.selectorLabels" . | nindent 4 }}
