image:
  repository: postgres
  tag: "16"
  pullPolicy: IfNotPresent

database:
  name: shelfsense_it
  username: shelfsense_user
  service:
    name: db
    port: 5432
  auth:
    password: ""

postgres:
  replicaCount: 1
  persistence:
    size: 1Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 6


backend:
  replicaCount: 2

  image:
    repository: shachafpardo/shelfsense-backend
    tag: "0.1.0"
    pullPolicy: IfNotPresent

  service:
    name: shelfsense-backend
    port: 8000

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

  readinessProbe:
    path: /ready
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6

  livenessProbe:
    path: /health
    initialDelaySeconds: 15
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 3